---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 11-jdk-slim

inputs:
  - name: app

caches:
  - path: cache

outputs:
  - name: jars

run:
  path: app/.concourse/tasks/build_java.sh
