name: Build project

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'liberica'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
